table Global-Superstore
	lineageTag: 8ec4ad39-f687-4c90-9bf6-82c1426e70ce

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 9d2ff639-da20-4b6e-9609-f1ff2bbfce0a
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: bc3fee42-c6cc-4673-88ac-17a9221bc691
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: string
		lineageTag: d781223f-bd56-41ee-af62-d134329db652
		summarizeBy: none
		sourceColumn: Order Date

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: string
		lineageTag: 67bcca03-5aeb-4fad-9526-5b2f9f7fb48f
		summarizeBy: none
		sourceColumn: Ship Date

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 6fcb15df-201b-4241-82d1-c816b143967f
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: a34d8c01-4274-4579-955a-beb0230b1a30
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 83a17b0b-0703-4d7d-9b37-bf6e200f706e
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 9579965c-0572-440f-91f7-ec1c5c4edc9b
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: e2360811-ead0-467a-a0d9-53195173c5ba
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: caba6def-bc91-4b33-a170-fa4731a52c4e
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: c8c5f505-7ead-4aac-bdba-1e91706621b5
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 54c90b95-3822-44ee-acda-185d58cf767d
		summarizeBy: count
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Market
		dataType: string
		lineageTag: 947c505a-8f51-4475-90f5-68ea90b78792
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: fd5a4b65-b09d-434c-b0ea-7a2cc7b0286e
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 16bd1ee5-f412-4d97-872c-f6a5ecf48e0f
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 1b416bfb-325c-46f1-a40e-76bf84c859c9
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 84a47bd8-1c02-4f40-b255-f50efeecc1b8
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 0f20e909-37f0-4d14-8064-6fec5b67fd58
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: int64
		formatString: 0
		lineageTag: cb0152ef-b804-443e-b86b-a7508e8a125f
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 4bfbe3fb-9565-4d17-a11f-a22eda24a6f0
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: int64
		formatString: 0
		lineageTag: 8cb88492-4908-448d-8c2b-7be6ca2ca3f7
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: int64
		formatString: 0
		lineageTag: 525f2644-128d-41fc-9d9e-2d94d7d8d17c
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column 'Shipping Cost'
		dataType: int64
		formatString: 0
		lineageTag: 94f1b0a9-49c3-4c0d-85f8-af973c8eb4b0
		summarizeBy: sum
		sourceColumn: Shipping Cost

		annotation SummarizationSetBy = Automatic

	column 'Order Priority'
		dataType: string
		lineageTag: 242db187-cf73-4c28-890f-c7577ff47b21
		summarizeBy: none
		sourceColumn: Order Priority

		annotation SummarizationSetBy = Automatic

	partition Global-Superstore = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\Thiago\OneDrive\Projetos PowerBI\projetos-powerbi\sales-analytics\Global-Superstore.csv"),[Delimiter=",", Columns=24, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type text}, {"Ship Date", type text}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"City", type text}, {"State", type text}, {"Country", type text}, {"Postal Code", Int64.Type}, {"Market", type text}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", Int64.Type}, {"Quantity", Int64.Type}, {"Discount", Int64.Type}, {"Profit", Int64.Type}, {"Shipping Cost", Int64.Type}, {"Order Priority", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

