table fa_casoshumanos_1994-2025
	lineageTag: dfda5934-9b7b-4a5e-b5f2-549173b237bf

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 43874666-7ddb-49fb-8952-3a4cabbb0092
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Região Sigla'
		dataType: string
		lineageTag: e7170d0c-0d49-475a-9d49-bbc501a32202
		summarizeBy: none
		sourceColumn: Região Sigla

		annotation SummarizationSetBy = Automatic

	column 'Código UF'
		dataType: int64
		formatString: 0
		lineageTag: c75a496d-7479-40cb-9013-34857f1630ca
		summarizeBy: sum
		sourceColumn: Código UF

		annotation SummarizationSetBy = Automatic

	column UF
		dataType: string
		lineageTag: cbaefad5-aa74-49ba-8f17-3fec455a9d42
		summarizeBy: none
		sourceColumn: UF

		annotation SummarizationSetBy = Automatic

	column 'Código Município'
		dataType: int64
		formatString: 0
		lineageTag: ada095c8-7ffd-4478-a134-d631cf927ca7
		summarizeBy: sum
		sourceColumn: Código Município

		annotation SummarizationSetBy = Automatic

	column Município
		dataType: string
		lineageTag: 1a46ac00-aad8-492a-abd4-6595746b0d8a
		summarizeBy: none
		sourceColumn: Município

		annotation SummarizationSetBy = Automatic

	column Sexo
		dataType: string
		lineageTag: e715eeb0-8919-489c-84c9-6d779fe26e1f
		summarizeBy: none
		sourceColumn: Sexo

		annotation SummarizationSetBy = Automatic

	column Idade
		dataType: double
		lineageTag: 9c36e8f2-48df-4185-9334-c47bb3146e92
		summarizeBy: sum
		sourceColumn: Idade

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Data Sintomas'
		dataType: string
		lineageTag: 74426ff5-8747-4dd4-a5c8-877ea469a0d6
		summarizeBy: none
		sourceColumn: Data Sintomas

		annotation SummarizationSetBy = Automatic

	column 'Semana Sintomas'
		dataType: int64
		formatString: 0
		lineageTag: c3c1f993-1fb9-4126-b4a7-1fa229dfb42e
		summarizeBy: sum
		sourceColumn: Semana Sintomas

		annotation SummarizationSetBy = Automatic

	column 'Mês Sintomas'
		dataType: int64
		formatString: 0
		lineageTag: 2e9ad697-8540-4c00-aabf-e2fcda095676
		summarizeBy: sum
		sourceColumn: Mês Sintomas

		annotation SummarizationSetBy = Automatic

	column 'Ano Sintomas'
		dataType: int64
		formatString: 0
		lineageTag: 3f26091d-ebf8-4d98-ab5a-b04e95ef7029
		summarizeBy: sum
		sourceColumn: Ano Sintomas

		annotation SummarizationSetBy = Automatic

	column 'Período Monitoria'
		dataType: string
		lineageTag: 3b707794-857d-41ec-8b64-659d455ff72d
		summarizeBy: none
		sourceColumn: Período Monitoria

		annotation SummarizationSetBy = Automatic

	column Óbito
		dataType: string
		lineageTag: fd39d72b-9c59-4912-819b-e238eec98855
		summarizeBy: none
		sourceColumn: Óbito

		annotation SummarizationSetBy = Automatic

	column 'Data Óbito'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6536f8df-87a6-426c-9cf4-c9b016e84c5f
		summarizeBy: none
		sourceColumn: Data Óbito

		variation Variation
			isDefault
			relationship: b5b87d96-66cd-496c-b0c0-175c9531c0a6
			defaultHierarchy: LocalDateTable_4a5b3025-b8ba-4b5b-b944-4fc7ebf1b3ae.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Região
		dataType: string
		lineageTag: a5b69f79-5218-425e-932e-b4ad90d6dd75
		summarizeBy: none
		sourceColumn: Região

		annotation SummarizationSetBy = Automatic

	column 'UF Ajustada'
		dataType: string
		lineageTag: b0a47bad-1672-4414-a2c8-99aa956da6b0
		summarizeBy: none
		sourceColumn: UF Ajustada

		annotation SummarizationSetBy = Automatic

	column 'Faixa Estária'
		dataType: string
		lineageTag: a6a46720-f24a-4304-960c-ea0d612fa689
		summarizeBy: none
		sourceColumn: Faixa Estária

		annotation SummarizationSetBy = Automatic

	partition fa_casoshumanos_1994-2025 = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\Thiago\OneDrive\Projetos PowerBI\projetos-powerbi\febre-amarela-br\fa_casoshumanos_1994-2025.csv"),[Delimiter=";", Columns=15, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID", Int64.Type}, {"MACRORREG_LPI", type text}, {"COD_UF_LPI", Int64.Type}, {"UF_LPI", type text}, {"COD_MUN_LPI", Int64.Type}, {"MUN_LPI", type text}, {"SEXO", type text}, {"IDADE", type number}, {"DT_IS", type text}, {"SE_IS", Int64.Type}, {"MES_IS", Int64.Type}, {"ANO_IS", Int64.Type}, {"MONITORAMENTO_IS", type text}, {"OBITO", type text}, {"DT_OBITO", type date}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"MACRORREG_LPI", "Região"}, {"COD_UF_LPI", "Código UF"}, {"UF_LPI", "UF"}, {"COD_MUN_LPI", "Código Município"}, {"MUN_LPI", "Município"}, {"SEXO", "Sexo"}, {"IDADE", "Idade"}, {"SE_IS", "Semana Sintomas"}, {"MES_IS", "Mês Sintomas"}, {"ANO_IS", "Ano Sintomas"}, {"MONITORAMENTO_IS", "Período Monitoria"}, {"OBITO", "Óbito"}, {"DT_OBITO", "Data Óbito"}, {"DT_IS", "Data Sintomas"}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Colunas Renomeadas", each true),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Linhas Filtradas",{{"Região", "Região Sigla"}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Colunas Renomeadas1", "Região", each if [Região Sigla] = "N" then "Norte" else if [Região Sigla] = "NE" then "Nordeste" else if [Região Sigla] = "CO" then "Centro-Oeste" else if [Região Sigla] = "SE" then "Sudeste" else if [Região Sigla] = "S" then "Sul" else null),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Coluna Condicional Adicionada",{"ID", "Região Sigla", "Região", "Código UF", "UF", "Código Município", "Município", "Sexo", "Idade", "Data Sintomas", "Semana Sintomas", "Mês Sintomas", "Ano Sintomas", "Período Monitoria", "Óbito", "Data Óbito"}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Colunas Reordenadas", each true),
				    #"Personalização Adicionada" = Table.AddColumn(#"Linhas Filtradas1", "UF Ajustada", each "Brasil - "&[UF]),
				    #"Colunas Reordenadas1" = Table.ReorderColumns(#"Personalização Adicionada",{"ID", "Região Sigla", "Região", "Código UF", "UF", "UF Ajustada", "Código Município", "Município", "Sexo", "Idade", "Data Sintomas", "Semana Sintomas", "Mês Sintomas", "Ano Sintomas", "Período Monitoria", "Óbito", "Data Óbito"}),
				    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(#"Colunas Reordenadas1",{{"Município", Text.Proper, type text}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Colocar Cada Palavra Em Maiúscula","IGN","NÃO",Replacer.ReplaceText,{"Óbito"}),
				    #"Linhas Filtradas2" = Table.SelectRows(#"Valor Substituído", each true),
				    #"Colocar Cada Palavra Em Maiúscula1" = Table.TransformColumns(#"Linhas Filtradas2",{{"Óbito", Text.Proper, type text}}),
				    #"Linhas Filtradas3" = Table.SelectRows(#"Colocar Cada Palavra Em Maiúscula1", each true),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Linhas Filtradas3","M","Masculino",Replacer.ReplaceText,{"Sexo"}),
				    #"Valor Substituído2" = Table.ReplaceValue(#"Valor Substituído1","F","Feminino",Replacer.ReplaceText,{"Sexo"}),
				    #"Linhas Filtradas4" = Table.SelectRows(#"Valor Substituído2", each true),
				    #"Linhas Filtradas5" = Table.SelectRows(#"Linhas Filtradas4", each [Idade] <> null and [Idade] <> ""),
				    #"Linhas Filtradas6" = Table.SelectRows(#"Linhas Filtradas5", each [Idade] <> null and [Idade] <> ""),
				    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Linhas Filtradas6", "Faixa Estária", each if [Idade] <= 12 then "Infantil" else if [Idade] <= 17 then "Adolescente" else if [Idade] <= 64 then "Adulto" else if [Idade] >= 65 then "Idoso" else null)
				in
				    #"Coluna Condicional Adicionada1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

