table fa_casoshumanos_1994-2025
	lineageTag: dfda5934-9b7b-4a5e-b5f2-549173b237bf

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 43874666-7ddb-49fb-8952-3a4cabbb0092
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column MACRORREG_LPI
		dataType: string
		lineageTag: e7170d0c-0d49-475a-9d49-bbc501a32202
		summarizeBy: none
		sourceColumn: MACRORREG_LPI

		annotation SummarizationSetBy = Automatic

	column COD_UF_LPI
		dataType: int64
		formatString: 0
		lineageTag: c75a496d-7479-40cb-9013-34857f1630ca
		summarizeBy: sum
		sourceColumn: COD_UF_LPI

		annotation SummarizationSetBy = Automatic

	column UF_LPI
		dataType: string
		lineageTag: cbaefad5-aa74-49ba-8f17-3fec455a9d42
		summarizeBy: none
		sourceColumn: UF_LPI

		annotation SummarizationSetBy = Automatic

	column COD_MUN_LPI
		dataType: int64
		formatString: 0
		lineageTag: ada095c8-7ffd-4478-a134-d631cf927ca7
		summarizeBy: sum
		sourceColumn: COD_MUN_LPI

		annotation SummarizationSetBy = Automatic

	column MUN_LPI
		dataType: string
		lineageTag: 1a46ac00-aad8-492a-abd4-6595746b0d8a
		summarizeBy: none
		sourceColumn: MUN_LPI

		annotation SummarizationSetBy = Automatic

	column SEXO
		dataType: string
		lineageTag: e715eeb0-8919-489c-84c9-6d779fe26e1f
		summarizeBy: none
		sourceColumn: SEXO

		annotation SummarizationSetBy = Automatic

	column IDADE
		dataType: double
		lineageTag: 9c36e8f2-48df-4185-9334-c47bb3146e92
		summarizeBy: sum
		sourceColumn: IDADE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DT_IS
		dataType: string
		lineageTag: 74426ff5-8747-4dd4-a5c8-877ea469a0d6
		summarizeBy: none
		sourceColumn: DT_IS

		annotation SummarizationSetBy = Automatic

	column SE_IS
		dataType: int64
		formatString: 0
		lineageTag: c3c1f993-1fb9-4126-b4a7-1fa229dfb42e
		summarizeBy: sum
		sourceColumn: SE_IS

		annotation SummarizationSetBy = Automatic

	column MES_IS
		dataType: int64
		formatString: 0
		lineageTag: 2e9ad697-8540-4c00-aabf-e2fcda095676
		summarizeBy: sum
		sourceColumn: MES_IS

		annotation SummarizationSetBy = Automatic

	column ANO_IS
		dataType: int64
		formatString: 0
		lineageTag: 3f26091d-ebf8-4d98-ab5a-b04e95ef7029
		summarizeBy: sum
		sourceColumn: ANO_IS

		annotation SummarizationSetBy = Automatic

	column MONITORAMENTO_IS
		dataType: string
		lineageTag: 3b707794-857d-41ec-8b64-659d455ff72d
		summarizeBy: none
		sourceColumn: MONITORAMENTO_IS

		annotation SummarizationSetBy = Automatic

	column OBITO
		dataType: string
		lineageTag: fd39d72b-9c59-4912-819b-e238eec98855
		summarizeBy: none
		sourceColumn: OBITO

		annotation SummarizationSetBy = Automatic

	column DT_OBITO
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6536f8df-87a6-426c-9cf4-c9b016e84c5f
		summarizeBy: none
		sourceColumn: DT_OBITO

		variation Variation
			isDefault
			relationship: b5b87d96-66cd-496c-b0c0-175c9531c0a6
			defaultHierarchy: LocalDateTable_4a5b3025-b8ba-4b5b-b944-4fc7ebf1b3ae.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition fa_casoshumanos_1994-2025 = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\Thiago\OneDrive\Projetos PowerBI\projetos-powerbi\febre-amarela-br\fa_casoshumanos_1994-2025.csv"),[Delimiter=";", Columns=15, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID", Int64.Type}, {"MACRORREG_LPI", type text}, {"COD_UF_LPI", Int64.Type}, {"UF_LPI", type text}, {"COD_MUN_LPI", Int64.Type}, {"MUN_LPI", type text}, {"SEXO", type text}, {"IDADE", type number}, {"DT_IS", type text}, {"SE_IS", Int64.Type}, {"MES_IS", Int64.Type}, {"ANO_IS", Int64.Type}, {"MONITORAMENTO_IS", type text}, {"OBITO", type text}, {"DT_OBITO", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

